# rating
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
spec:
  selector:
    matchLabels:
      app: rating
  replicas: {{ .Values.app.rating.replicaCount }}
  template: 
    metadata:
      labels:
        version: original
        app: rating
    spec:
      containers:
      - name: rating-container
        image: {{ .Values.image.repository }}/rating-service:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8081
        envFrom: 
        - configMapRef:
            name: service-url
        - configMapRef:
            name: app-db-setting
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 80
          periodSeconds: 10
          
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 80
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name:  rating-service
spec:
  selector:
    app: rating
  ports:
    - name: http
      port: 8080
      targetPort: 8081
  type: ClusterIP

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rating
  namespace: default
  annotations:
    metric-config.object.istio-requests-total.prometheus/per-replica: "true"
    metric-config.object.istio-requests-total.prometheus/query: |
      sum(
          rate(
              istio_requests_total{
                destination_workload="rating",
                destination_workload_namespace="default",
                reporter="destination"
              }[1m]
          )
      ) /
      count(
        count(
          container_memory_usage_bytes{
            namespace="default",
          pod=~"rating.*"
          }
        ) by (pod)
      )
spec:
  maxReplicas: {{ .Values.hpa.rating.maxReplicas }}
  minReplicas: {{ .Values.hpa.rating.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rating
  metrics:
    - type: Object
      object:
        metric:
          name: istio-requests-total
        describedObject:
          apiVersion: v1
          kind: Pod
          name: rating
        target:
          type: Value
          value: {{ .Values.hpa.rating.targetValue }}
