# api gate way
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: {{ .Values.app.apiGateWay.replicaCount }}
  template: 
    metadata:
      labels:
        app: gateway
    spec:
    # {{ .Values.image.repository}}/gateway-service:{{ .Values.image.tag }}
      containers:
      - name: apigateway-container
        image: {{ .Values.image.repository}}/nginx-gateway:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        envFrom: 
        - configMapRef:
            name: service-url

        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 80
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 80
          periodSeconds: 10
      
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 8080
      targetPort: 80
  type: ClusterIP


---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apigateway
  namespace: default
  annotations:
    metric-config.object.istio-requests-total.prometheus/per-replica: "true"
    metric-config.object.istio-requests-total.prometheus/query: |
      sum(
          rate(
              istio_requests_total{
                destination_workload="apigateway",
                destination_workload_namespace="default",
                reporter="destination"
              }[1m]
          )
      ) /
      count(
        count(
          container_memory_usage_bytes{
            namespace="default",
          pod=~"apigateway.*"
          }
        ) by (pod)
      )
spec:
  maxReplicas: {{ .Values.hpa.apiGateway.maxReplicas }}
  minReplicas: {{ .Values.hpa.apiGateway.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apigateway
  metrics:
    - type: Object
      object:
        metric:
          name: istio-requests-total
        describedObject:
          apiVersion: v1
          kind: Pod
          name: apigateway
        target:
          type: Value
          value: {{ .Values.hpa.apiGateway.targetValue }}